/** Educational analogies, not statements about today's market. */
export const LEARNING_USAGE: Record<string, { example: string; todayUsage: string }> = {
  'price-earnings-ratio': { example: '像評估一家店：你願意花多少價格，換取它一年賺的錢？還要考慮未來獲利是否會變。', todayUsage: '把獲利成長和價格一起看；公司好，不代表任何價格都值得買。' },
  'price-to-book-ratio': { example: '像買店面時核對帳上資產，但帳面價值不一定是現在能賣出的價格。', todayUsage: '比較資產型公司時，同時看資產品質；低於一倍不等於被錯殺。' },
  'dividend-yield': { example: '像租金相對房價的比例；比例高，也可能只是房價下跌了。', todayUsage: '檢查配息能否持續，以及股價風險，不用高殖利率取代進場評估。' },
  eps: { example: '像把店的獲利分成相同份數，看每份分到多少；股份增加也會改變結果。', todayUsage: '確認成長來自本業還是一次性收益，再判斷事件是否真正改善獲利。' },
  revenue: { example: '店裡收進很多錢，不代表最後賺很多，還得扣掉進貨與營運費用。', todayUsage: '核對營收變化的需求、匯率與併購因素，不直接推論獲利同步增加。' },
  'gross-margin': { example: '飲料賣 100 元，直接成本 60 元，剩下 40 元仍要付房租等其他費用。', todayUsage: '檢查訂單增加是否伴隨成本上升，利多不一定能等比例變成利潤。' },
  roe: { example: '像看店主投入的資本產生多少獲利，但大量借錢也可能讓表面效率變高。', todayUsage: '一起看負債與一次性收益，不單靠高 ROE 提高模型信心。' },
  long: { example: '像先買下商品，期待以後價值提高；期待不是保證，價格仍可能下跌。', todayUsage: '把方向偏多與現在是否值得進場分開，偏多也可能要等待。' },
  'short-selling': { example: '像先借商品賣掉，之後買回歸還；若價格變貴，買回成本也會增加。', todayUsage: '報告偏空是風險判斷，不等於放空指令；需另外理解回補與借券限制。' },
  'margin-financing': { example: '像借錢放大購買金額，價格下跌時，自有資金的損失比例也會放大。', todayUsage: '留意槓桿是否放大市場壓力；高信心不能消除追繳風險。' },
  'securities-lending': { example: '像暫借物品，用途不只一種；只看借用數量，不能確定每個人的目的。', todayUsage: '分開看借券與借券賣出，不把借券增加直接當成股價將跌的證據。' },
  'day-trading': { example: '像同一天買入又賣出商品，時間短不代表沒有成本或價格風險。', todayUsage: '核對交易成本與自身風險承受度，盤中更新不是當沖口令。' },
  'stop-loss': { example: '像出門前先決定什麼情況要折返，不等遇到危險才臨時想辦法。', todayUsage: '先讀失效條件；觸發時重新評估，但跳空與流動性仍會影響成交。' },
  'chasing-price': { example: '像看見大家排隊，就願意高價買同一件商品；熱度增加不代表價值等幅增加。', todayUsage: '遇到「看多但不追」時，檢查價格已反映多少利多，以及風險報酬是否仍合理。' },
  'position-size': { example: '像旅行預算不能全花在第一站，得保留承受意外的空間。', todayUsage: '研究評估不是投入比例指令；先考慮集中度與可承受損失。' },
  'trading-volume': { example: '像店裡成交變熱絡，但人多不代表每個人看好或看壞的理由相同。', todayUsage: '搭配價格與同時段基準看量，不能直接用未收盤的量比較完整一天。' },
  'moving-average': { example: '像最近幾天平均氣溫，可平滑單日變化，但比最新天氣反應慢。', todayUsage: '觀察趨勢與價格位置，不把站上均線單獨當成劇本已成立。' },
  support: { example: '像曾有人願意接手的價格區，下一次到那裡不保證還有人接。', todayUsage: '核對實際承接證據；支撐失守是待核對的條件，不是寫下就算發生。' },
  resistance: { example: '像過去常有人願意出售的價格區，能否通過仍要看這次買賣力量。', todayUsage: '區分正在測試與已完成突破，不提前宣告成功。' },
  breakout: { example: '像走出原本活動範圍，還要確認不是立刻退回的一次試探。', todayUsage: '一起核對價格、量能與維持情況，一根紅 K 不保證突破有效。' },
  divergence: { example: '像速度表與引擎聲出現不同訊號，值得檢查，但不能只憑一個就斷定故障。', todayUsage: '將不一致列為反證，再等實際驗證，不直接宣告反轉。' },
  'price-volume': { example: '價格是成交價，量是交易熱度；兩者一起看，比只看其中一個完整。', todayUsage: '把量價現象搭配事件與基本面看，不用固定口訣替代證據。' },
  'foreign-investors': { example: '像背景不同的買家被放進同一張表，合計買多不代表目的都相同。', todayUsage: '核對日期、個股與市場總額，不把一天買超當成未來價格保證。' },
  'investment-trusts': { example: '像不同基金經理人的交易合計，資金流入與成分調整都會影響買賣。', todayUsage: '看連續性、價格與基本面，不只追逐單日買超排行。' },
  dealers: { example: '像商店有自己的庫存，也會為客戶需求調整存貨，不全是方向押注。', todayUsage: '分開看自行買賣與避險，不把自營商買超一律當成看多。' },
  'institutional-investors': { example: '像把幾類大型買家放在一起看，但每群人的用途與時間長度不同。', todayUsage: '拆看外資、投信與自營商，確認是否同步，不只看合計數字。' },
  'market-operator': { example: '像從腳印猜誰來過，只能形成線索，不能確定身分與計畫。', todayUsage: '先問資料來源，不把無法核對的身分猜測當成推薦證據。' },
  'confirmation-condition': { example: '像出發前檢查車況，寫下「煞車正常」不等於已經實際檢查。', todayUsage: '分開看條件描述與完成證據，真正完成驗證才可升級判斷。' },
  'invalidation-condition': { example: '像預先決定什麼天氣要取消活動，列出條件不代表現在已經發生。', todayUsage: '先了解何事會推翻劇本，不能只因文中出現「跌破」就判定失敗。' },
  'relative-market': { example: '像比較自己與同場跑者的速度，跑得較快也可能都在下坡。', todayUsage: '個股比大盤強不等於一定上漲，同時看絕對報酬與市場方向。' },
  'beneficiary-stock': { example: '像街區增加人潮，真正受益的是能轉成人流生意的店，不是附近每家店。', todayUsage: '沿事件、產業、公司曝險與獲利影響核對，再看價格是否已反映利多。' },
  'evidence-coverage': { example: '像每個結論都有收據可核對，但收據多不保證判斷必然正確。', todayUsage: '核對來源與時間；覆蓋率不是模型命中率，也不是買進機率。' },
  'decision-snapshot': { example: '像交卷時保存答案，不能知道成績後再改寫當時答案。', todayUsage: '對照盤前原判斷、後續新增證據與收盤結果，不將事後修正冒充事前已知。' },
};
